apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-1ewu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/lpardo-tenant/pt-go-sample/devfile-sample-go-basic-1ewu@sha256:35cf2ad3c2ac7b4a3925012f96b31bb990cba250a1716b03f093bc4328d95cf8
        name: my-go
        resources: {}
status: {}
