apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-1ewu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-1ewu
    app.kubernetes.io/part-of: pt-go-sample
  name: devfile-sample-go-basic-1ewu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-1ewu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-1ewu
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/lpardo-tenant/pt-go-sample/devfile-sample-go-basic-1ewu@sha256:35cf2ad3c2ac7b4a3925012f96b31bb990cba250a1716b03f093bc4328d95cf8
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
